import { act, fireEvent, render, screen } from '@testing-library/react'
import { beforeEach, describe, expect, it } from 'vitest'
import { applyDrawTool, currentPrompt, useCadStore } from '../core/store'
import { makeDefaultDocument } from '../core/document'
import { createLine } from '../core/commands'
import { CommandLine } from './CommandLine'

/**
 * Every command whose prompt offers a bracketed option, and what that option is meant to move.
 *
 * The options live in two places at once: a button in the prompt, which goes straight to the store,
 * and the letters in the brackets, which are typed into the command line. Typing must land on the
 * same option the button does — the command line is the only route that exists on a phone, and it is
 * the one that used to "helpfully" complete `T` to TEXT, `S` to SAVE and `R` to RECTANG, so a whole
 * sub-menu ran a different command instead of picking the option.
 */

const state = () => useCadStore.getState()
const run = (line: string) => act(() => state().executeCommand(line))

/** The fields an option is supposed to move. Everything else in the store is noise here. */
const WATCHED = [
  'activeTool',
  'pickingEdges',
  'edgeIds',
  'circleMode',
  'circlePending',
  'arcMode',
  'rectMode',
  'rectPending',
  'polygonFit',
  'hatchPattern',
  'hatchPending',
  'arrayType',
  'arrayPending',
  'arrayRotateItems',
  'offsetThrough',
  'offsetErase',
  'offsetToCurrentLayer',
  'cornerPending',
  'mirrorKeepSource',
  'draftPoints',
  'statusMessage',
] as const

const snapshot = (): Record<string, unknown> => {
  const current = state() as unknown as Record<string, unknown>
  const picked: Record<string, unknown> = {}
  for (const key of WATCHED) picked[key] = current[key]
  picked.entities = state().doc.entities.length
  // Ids are regenerated by each reseed, so the count is what an option could have changed.
  picked.selectionCount = state().selectedIds.length
  return picked
}

const additions = (copy: ReturnType<typeof createLine>[]): void => {
  state().updateDocument((doc) => ({ ...doc, entities: [...doc.entities, ...copy] }))
}

/** Objects in the drawing, selected, for the commands that act on a selection. */
const withSelection = () => {
  const drawn = createLine(state().doc.layers[0].id, { x: 0, y: 0 }, { x: 10, y: 0 })
  additions([drawn])
  act(() => state().setSelection([drawn.id]))
}

/**
 * Back to a clean sheet. The per-command options outlive a cancelled command — and an option that
 * cycles (the hatch pattern) or toggles (Rotate items) is not idempotent — so both paths have to
 * start from the same values or the comparison reports a difference the fix did not cause.
 */
const reset = () => {
  act(() => {
    state().cancelCommand()
    state().updateDocument(() => makeDefaultDocument())
    useCadStore.setState({
      history: [],
      statusMessage: undefined,
      selectedIds: [],
      arrayType: 'rect',
      arrayPending: null,
      arrayRotateItems: false,
      polygonFit: 'inscribed',
      hatchPending: null,
      hatchPattern: 'ansi31',
      offsetThrough: false,
      offsetErase: false,
      offsetToCurrentLayer: false,
      cornerPending: false,
      edgeIds: null,
      pickingEdges: false,
      mirrorKeepSource: true,
      circleMode: 'center',
      arcMode: 'cse',
      rectMode: 'corners',
      rectPending: null,
      insertBlockId: null,
      blockNamePending: false,
    })
    state().setCommandInput('')
  })
}

/** Puts a command at the prompt whose options are under test. */
type Setup = { name: string; setup: () => void }

const setups: Setup[] = [
  { name: 'LINE', setup: () => { run('LINE'); act(() => applyDrawTool({ x: 0, y: 0 })) } },
  { name: 'PLINE', setup: () => { run('PLINE'); act(() => applyDrawTool({ x: 0, y: 0 })) } },
  { name: 'RECTANG corners', setup: () => run('RECTANG') },
  {
    name: 'RECTANG from its centre',
    setup: () => {
      run('RECTANG')
      act(() => state().setRectMode('center'))
    },
  },
  {
    name: 'RECTANG corner picked',
    setup: () => {
      run('RECTANG')
      act(() => applyDrawTool({ x: 0, y: 0 }))
    },
  },
  { name: 'CIRCLE', setup: () => run('CIRCLE') },
  { name: 'CIRCLE radius', setup: () => { run('CIRCLE'); act(() => applyDrawTool({ x: 0, y: 0 })) } },
  { name: 'ARC', setup: () => run('ARC') },
  { name: 'ARRAY', setup: () => run('ARRAY') },
  {
    name: 'ARRAY rectangular',
    setup: () => {
      withSelection()
      run('ARRAY')
    },
  },
  {
    name: 'ARRAY polar',
    setup: () => {
      withSelection()
      run('ARRAY')
      act(() => state().setArrayType('polar'))
    },
  },
  { name: 'POLYGON', setup: () => run('POLYGON') },
  { name: 'HATCH', setup: () => run('HATCH') },
  { name: 'OFFSET distance', setup: () => run('OFFSET') },
  { name: 'OFFSET object', setup: () => { run('OFFSET'); act(() => state().applyKeyword({ key: 'T', label: 'Through' })) } },
  { name: 'TRIM', setup: () => run('TRIM') },
  { name: 'TRIM picking edges', setup: () => { run('TRIM'); act(() => state().beginEdgeSelection()) } },
  { name: 'EXTEND', setup: () => run('EXTEND') },
  { name: 'FILLET', setup: () => run('FILLET') },
  { name: 'CHAMFER', setup: () => run('CHAMFER') },
  {
    name: 'MIRROR',
    setup: () => {
      withSelection()
      run('MIRROR')
    },
  },
]

/** Types `text` at the real command line and presses Enter, as a user does. */
const typeAndEnter = (text: string) => {
  const input = screen.getByRole('textbox')
  fireEvent.change(input, { target: { value: text } })
  fireEvent.keyDown(input, { key: 'Enter' })
}

beforeEach(reset)

describe('a prompt option typed at the command line', () => {
  it('does what the same option does when it is clicked, for every command that offers one', () => {
    render(<CommandLine />)
    const mismatches: string[] = []

    for (const entry of setups) {
      reset()
      entry.setup()
      const keywords = currentPrompt(state()).keywords
      if (keywords.length === 0) throw new Error(`${entry.name} was expected to offer options`)

      for (const keyword of keywords) {
        // The option clicked in the prompt.
        reset()
        entry.setup()
        act(() => state().applyKeyword(keyword))
        const clicked = snapshot()

        // The same option typed as its letters.
        reset()
        entry.setup()
        typeAndEnter(keyword.key)
        const typed = snapshot()

        const differs = WATCHED.filter(
          (field) => JSON.stringify(clicked[field]) !== JSON.stringify(typed[field]),
        )
        if (differs.length > 0) {
          const detail = differs
            .map((field) => `${field}: clicked=${JSON.stringify(clicked[field])} typed=${JSON.stringify(typed[field])}`)
            .join(', ')
          mismatches.push(`${entry.name} [${keyword.key} → ${keyword.label}] ${detail}`)
        }
      }
    }

    expect(mismatches).toEqual([])
  })

  it('cuts the edges during TRIM rather than starting TEXT', () => {
    // T is TRIM's keyword for its cutting edges and the first letter of TEXT, which the completion
    // used to take — so the option silently handed the command over to another one.
    render(<CommandLine />)
    run('TRIM')

    typeAndEnter('T')

    expect(state().activeTool).toBe('trim')
    expect(state().pickingEdges).toBe(true)
  })

  it('takes S as the hatch scale rather than saving the drawing', () => {
    // SAVE is what `S` completed to, and the command line runs file commands itself, so the option
    // downloaded the drawing and left the hatch exactly as it was.
    render(<CommandLine />)
    run('HATCH')

    typeAndEnter('S')

    expect(state().hatchPending).toBe('scale')
    expect(state().activeTool).toBe('hatch')
  })

  it('offers no command suggestions while what is typed is one of the prompt options', () => {
    render(<CommandLine />)
    run('TRIM')
    // TRIM's options are on show, so TEXT must not be advertised underneath them.
    expect(screen.queryByText('TEXT')).toBeNull()

    fireEvent.change(screen.getByRole('textbox'), { target: { value: 'T' } })

    expect(screen.queryByText('TEXT')).toBeNull()
  })

  it('still suggests commands when what is typed reaches no option', () => {
    render(<CommandLine />)
    run('TRIM')

    // "TEX" is the start of TEXT and of nothing TRIM offers, so the suggestion stays available.
    fireEvent.change(screen.getByRole('textbox'), { target: { value: 'TEX' } })

    expect(screen.getByText('TEXT')).toBeInTheDocument()
  })
})
